### ISSUE TITLE
Sanity V3 - Failed to resolve entry for the package "yoastseo"

### ISSUE THREAD

**Issue by thartman94** [LiamMartens/sanity-plugin-seo-tools#64]
Seeing this error when trying to run on Sanity V3:

```
node_modules/vite/node_modules/esbuild/lib/main.js:1336:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "yoastseo". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/home/tom/work/projects/static-v2/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1575:15)
    at /home/tom/work/projects/static-v2/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/home/tom/work/projects/static-v2/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/home/tom/work/projects/static-v2/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1031:7)
    at /home/tom/work/projects/static-v2/studio/node_modules/vite/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/home/tom/work/projects/static-v2/studio/node_modules/vite/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/home/tom/work/projects/static-v2/studio/node_modules/vite/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/home/tom/work/projects/static-v2/studio/node_modules/vite/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
```

**Comment by aascione-mw** [comment]
I am experiencing the same on Sanity V3, but not on V2. It seems to be related to vite and the resolution of the 'yoastseo' module.
Could you please give us a workaroung/fix?

**Comment by Designer023** [comment]
I'm getting the same issue

**Comment by stijnelskens** [comment]
Same here!
Any updates?

**Comment by thartman94** [comment]
did some more digging, looks like the issue is actually with yoast themselves and not sanity-plugin-seo-tools. Here's a related issue i found: https://github.com/Yoast/wordpress-seo/issues/19359

**Comment by Designer023** [comment]
> did some more digging, looks like the issue is actually with yoast themselves and not sanity-plugin-seo-tools. Here's a related issue i found: [Yoast/wordpress-seo#19359](https://github.com/Yoast/wordpress-seo/issues/19359)

From what I can see, that is merged and released, so it may just be a simple as bumpling the `yoastseo` package in this repo up to `1.91.1`.

**Comment by Designer023** [comment]
Awesome. Thank you for making the update so quickly 😄

**Comment by Designer023** [comment]
👏 Installed, added `yoastseo`, and updated my `structure` with the config. Working like a charm. Thank you again 👍

**Comment by thartman94** [comment]
I tried integrating the updated package but am now seeing this error - "TypeError: _util2.default.inherits is not a function". Is anyone else having this issue?

**Comment by JustinKasad** [comment]
I'm seeing the same error.  @thartman94 Did you find a solution?
